### ISSUE TITLE
duplicate sms backup

### ISSUE THREAD

**Issue by nikulvasundhara** [kobeumut/uBackup-SMS#1]
if we restore our backup then sms are write morethan 2 times means duplication created.
- it will restore sms backup with existing sms and new one from backup file 
- if you restore sms from same backup file ex. 5 times then same sms create 5 times please solved this issue.

**Comment by kobeumut** [comment]
Hello @nikulvasundhara,
Sms are not checked again in the restore process. So if you do restore when you have same text messages it will be duplicated.
